Talk.WebApp/Models/Friend/FriendInfoViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Talk.WebApp.Models.Friend
{
    /// <summary>
    /// Zobrazení uživatelských dat přítele.
    /// </summary>
    public class FriendInfoViewModel
    {
        /// <summary>
        /// Id uživatele.
        /// </summary>
        public int UserId { get; set; }

        /// <summary>
        /// Uživatelské jméno.
        /// </summary>
        [Display(Name = "Uživatelské jméno")]
        public string Name { get; set; }

        /// <summary>
        /// Emailová adresa.
        /// </summary>
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// Je administrátor?
        /// </summary>
        [Display(Name = "Je admin")]
        public bool IsAdmin { get; set; }
    }
}

Talk.WebApp/Models/Friend/FriendTalkViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Talk.WebApp.Models.Friend
{
    /// <summary>
    /// Komu posílám zprávu + seznam posledních zpráv.
    /// </summary>
    public class FriendTalkViewModel
    {
        /// <summary>
        /// Moje jméno.
        /// </summary>
        public string MyName { get; set; }

        /// <summary>
        /// (User)Id přítele.
        /// </summary>
        public int FriendId { get; set; }

        /// <summary>
        /// Jméno přítele.
        /// </summary>
        public string FriendName { get; set; }

        /// <summary>
        /// Sezmam poslední komunikace.
        /// </summary>
        public IList<MessageViewModel> LastMessages { get; set; }
    }
}

Talk.WebApp/Models/Friend/FriendViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Talk.WebApp.Models.Friend
{
    /// <summary>
    /// Model pro seznam přátel.
    /// </summary>
    public class FriendViewModel
    {
        /// <summary>
        /// Id uživatele.
        /// </summary>
        public int UserId { get; set; }

        /// <summary>
        /// Uživ. jméno osoby.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Počet zpráv.
        /// </summary>
        public int? CountMessages { get; set; }

        /// <summary>
        /// Počet odeslaných zpráv.
        /// </summary>
        public int? CountSentMessages { get; set; }

        /// <summary>
        /// Počet doručených zpráv.
        /// </summary>
        public int? CountRecivedMessage { get; set; }

        /// <summary>
        /// Poslední odeslaná zpráva.
        /// </summary>
        public int? LastSentMessageId { get; set; }

        /// <summary>
        /// Poslední přijatá zpráva.
        /// </summary>
        public int? LastRecivedMessageId { get; set; }

        /// <summary>
        /// Datum poslední zprávy.
        /// </summary>
        public DateTime? LastMessageDate { get; set; }

        /// <summary>
        /// Text poslední zprávy
        /// </summary>
        public string LastMessageText { get; set; }
    }
}

Talk.WebApp/Models/Friend/MessageViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Talk.WebApp.Models.Friend
{
    /// <summary>
    /// Jedna zpráva.
    /// </summary>
    public class MessageViewModel
    {
        /// <summary>
        /// Id zprávy.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Datum a čas vytvoření.
        /// </summary>
        public DateTime Created { get; set; }

        /// <summary>
        /// Odeslal.
        /// </summary>
        public int From { get; set; }

        /// <summary>
        /// Obdržel.
        /// </summary>
        public int To { get; set; }

        /// <summary>
        /// Je to moje zpráva ?
        /// </summary>
        public bool IsMine { get; set; }

        /// <summary>
        /// Text zprávy.
        /// </summary>
        public string Text { get; set; }
    }
}

Talk.WebApp/Components/PagerViewComponent.cs
using Talk.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace Talk.WebApp.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(PagingInfo model) => this.View(model);
    }
}

Talk.WebApp/Controllers/FriendController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;
using Talk.Data.Model;
using Talk.WebApp.Models;
using Talk.WebApp.Models.Friend;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Microsoft.Extensions.Logging;

namespace Talk.WebApp.Controllers
{
    [Route("Friend"), Authorize]
    public class FriendController : Controller
    {
        private readonly ILogger _logger;

        private readonly AppConfiguration _cfg;

        private readonly TalkDbContext _dc;

        private readonly UserManager<ApplicationUser> _userManager;


        // Constructor
        public FriendController(ILoggerFactory loggerFactory, IOptionsSnapshot<AppConfiguration> optionsSnapshot, UserManager<ApplicationUser> userManager, TalkDbContext dc)
        {
            this._logger = loggerFactory.CreateLogger<FriendController>();
            this._cfg = optionsSnapshot.Value;
            this._dc = dc;
            this._userManager = userManager;
        }

        // Actions

        //
        // GET: /Friend/Call
        [HttpGet, Route("Call/{pageNumber:int:min(1)=1}")]
        public async Task<IActionResult> Call(int pageNumber)
        {
            int myUserId = (await GetCurrentUserAsync()).Id;

            var query = this._dc.Users
                .Where(u => u.Id != myUserId)
                .Select(u => new FriendViewModel()
                {
                    UserId = u.Id,
                    Name = u.UserName,

                    CountSentMessages = u.MessagesSent.Count(m => m.UserReceivedId == myUserId),
                    CountRecivedMessage = u.MessagesRecived.Count(m => m.UserSentId == myUserId),

                    LastSentMessageId = u.MessagesSent.Where(m => m.UserReceivedId == myUserId).Max(m => (int?)m.Id),
                    LastRecivedMessageId = u.MessagesRecived.Where(m => m.UserSentId == myUserId).Max(m => (int?)m.Id)
                })
                .OrderByDescending(x => x.LastRecivedMessageId)
                .ThenBy(x => x.Name);

            var model = new PagedModel<FriendViewModel>();
            model.GetData(query, pageNumber, this._cfg.PageSize).ForEach(friend =>
            {
                friend.CountMessages = friend.CountSentMessages + friend.CountRecivedMessage;

                int lastMessageId = friend.LastRecivedMessageId.GetValueOrDefault(0) > friend.LastSentMessageId.GetValueOrDefault(0) ?
                    friend.LastRecivedMessageId.GetValueOrDefault(0) : friend.LastSentMessageId.GetValueOrDefault(0);

                if (lastMessageId != 0)
                {
                    Message message = this._dc.Messages.First(m => m.Id == lastMessageId);
                    friend.LastMessageDate = message.DateCreated;
                    friend.LastMessageText = message.MessageText;
                }
            });

            return this.View(model);
        }

        //
        // GET: /Friend/Talk/{friend}
        [HttpGet, Route("Talk/{id:int:min(1)}")]
        public async Task<IActionResult> Talk(int id)
        {
            var appUser = await GetCurrentUserAsync();
            int myUserId = appUser.Id;

            var model = await this._dc.Users
                .Where(u => u.Id == id)
                .Select(u => new FriendTalkViewModel()
                {
                    MyName = appUser.UserName,
                    FriendId = u.Id,
                    FriendName = u.UserName
                })
                .SingleOrDefaultAsync();

            if (model == null)
                return this.NotFound();

            String group = String.Concat(Math.Min(model.FriendId, myUserId), ':', Math.Max(model.FriendId, myUserId));

            model.LastMessages = await this._dc.Messages
                .Where(m => m.Group.Equals(group))
                .OrderByDescending(m => m.DateCreated)
                .Take(_cfg.ViewLastMsg)
                .Select(m => new MessageViewModel()
                {
                    Id = m.Id,
                    Created = m.DateCreated,
                    From = m.UserSentId,
                    To = m.UserReceivedId,
                    IsMine = m.UserSentId == myUserId,
                    Text = m.MessageText
                })
                .ToListAsync();

            model.LastMessages = model.LastMessages.OrderBy(m => m.Created).ToList();
            return this.View(model);
        }

        //
        // GET: /Friend/Info/{friend}
        [HttpGet, Route("Info/{id:int:min(1)}")]
        public async Task<IActionResult> Info(int id)
        {
            ApplicationUser user = await _userManager.Users.FirstOrDefaultAsync(u => u.Id == id);

            FriendInfoViewModel model = new FriendInfoViewModel();
            if (user != null)
            {
                model.UserId = user.Id;
                model.Name = user.UserName;
                model.Email = user.Email;
                model.IsAdmin = await _userManager.IsInRoleAsync(user, "admin");
            }

            return View(model);
        }

        #region Helpers

        private Task<ApplicationUser> GetCurrentUserAsync()
        {
            return _userManager.GetUserAsync(HttpContext.User);
        }

        #endregion
    }
}

Talk.WebApp/Views/Friend/Call.cshtml
@model PagedModel<FriendViewModel>
@{
    this.ViewBag.Title = "Přátelé";
}
    <h2>@ViewData["Title"].</h2>
    <h4>Seznam přátel k rozhovoru.</h4>
    <hr />
@if (Model != null && Model.Data != null) {
    <div class="list-group">
        @foreach (FriendViewModel friend in Model.Data)
        {
            <a class="list-group-item list-group-item-action flex-column" asp-controller="Friend" asp-action="Talk" asp-route-id="@friend.UserId">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">@friend.Name</h5>
                    <small>@string.Format("{0:ddd d.M HH:mm}", friend.LastMessageDate) <span class="badge badge-primary badge-pill">@friend.CountMessages</span></small>
                </div>
                <p class="mb-1">@friend.LastMessageText</p>
            </a>
        }
    </div>
    <vc:pager model="Model.Paging"></vc:pager>
}

Talk.WebApp/Views/Friend/Info.cshtml
@model FriendInfoViewModel
@{
    this.ViewBag.Title = "Přítel";
}
<h2>@Model.Name</h2>
<h4>Informace o příteli.</h4>
<table class="table">
    <tbody>
        <tr>
            <td class="text-sent">Jméno</td>
            <td>@Model.Name</td>
        </tr>
        <tr>
            <td class="text-sent">Email</td>
            <td>@Model.Email</td>
        </tr>
        <tr>
            <td class="text-sent">Je administrátor ?</td>
            <td>@(Model.IsAdmin ? "ano - administrator" : "ne - uživatel")</td>
        </tr>
    </tbody>
</table>
<a class="" asp-area="" asp-controller="Friend" asp-action="Talk" asp-route-id="@Model.UserId">Zprávy</a>

Talk.WebApp/Views/Friend/Talk.cshtml
@model FriendTalkViewModel
@{
    ViewData["Title"] = "Rozhovor";
}
<h2>Rozhovor s <a class="text-sent" asp-area="" asp-controller="Friend" asp-action="Info" asp-route-id="@Model.FriendId">@Model.FriendName</a></h2>
<hr />
<div class="container">
    <div class="msg_history" id="msg_list">
        @if (Model.LastMessages != null && Model.LastMessages.Count > 0)
        {
            foreach (var msg in Model.LastMessages)
            {
                if (msg.IsMine)
                {
                    <div class="outgoing_msg">
                        <div class="sent_msg">
                            <plainText Text="@msg.Text" />
                            <span class="time_date">@String.Format("{0:HH:mm} | {0:ddd d.M}", @msg.Created)</span>
                        </div>
                    </div>
                }
                else
                {
                    <div class="incoming_msg">
                        <div class="received_msg">
                            <p>@msg.Text</p>
                            <span class="time_date">@String.Format("{0:HH:mm} | {0:ddd d.M}", @msg.Created)</span>
                        </div>
                    </div>
                }
            }
        }
    </div>
    <div class="type_msg">
        <div class="input_msg_write">
            <input type="hidden" id="userInput" value="@Model.FriendName" />
            <input type="text" id="messageInput" class="write_msg" placeholder="Napiště zprávu" />
            <button id="sendButton" class="msg_send_btn" type="button">Odeslat</button>
        </div>
    </div>
</div>
@section Scripts {
    <script src="~/lib/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/chat.js"></script>
}